- source/api-reference.html.md.erb
- source/integrating-with-the-dcs.html.md.erb
- source/partials/_links.erb
- source/status-response-codes.html.md.erb
The PR contains:
- changes requested by Lois - mainly rephrasing for readability and consistency
- rephrasing API message filed descriptions to have more readable sentences
> API reference edits

- config/tech-docs.yml
- source/accessibility-statement.html.md.erb
- source/api-reference.html.md.erb
- source/index.html.md.erb
- source/integrating-with-the-dcs.html.md.erb
- source/javascripts/application.js
- source/message-flow.html.md.erb
- source/message-structure.html.md.erb
- source/status-response-codes.html.md.erb
- source/support.html.md.erb
Add configuration for Daniel the Manual Spaniel. 
PR connecting Daniel to https://github.com/alphagov/tech-docs-monitor/pull/12. 
This also addresses an open issue: https://github.com/alphagov/dcs-pilot-docs/issues/61.
Because we want to keep our docs up to date, we should be reviewing them regularly.
Check the review dates make sense.
> Add Daniel the Manual Spaniel

- source/api-reference.html.md.erb
- source/index.html.md.erb
- source/integrating-with-the-dcs.html.md.erb
- source/message-flow.html.md.erb
- source/status-response-codes.html.md.erb
> Review stale pages.

- source/api-reference.html.md.erb
- Document response for http 503 during scheduled downtime.
> DCS: Scheduled Downtime Message

- source/api-reference.html.md.erb
- source/support.html.md.erb
Nothing new has been introduced that may require changes.
> Update review dates

- source/index.html.md.erb
- source/integrating-with-the-dcs.html.md.erb
- source/message-flow.html.md.erb
- source/status-response-codes.html.md.erb
No need to update page content
> Updating last_reviewed

- source/message-structure.html.md.erb
> BAU: Review "Message Structure"

- source/api-reference.html.md.erb
Manuel was complaining. 🐶 
Just updated the last_reviewed key. There doesn't seem to have been any changes to the relevant code.
> BAU: update manuel

- source/support.html.md.erb
Periodic review, no changes to add.
Bump `last_reviewed_on` to today.
> BAU: Review 'Support' page

- source/api-reference.html.md.erb
I don't think we've made any changes we need to reflect here in the past 3 weeks...
> BAU: review API reference

- source/index.html.md.erb
- source/integrating-with-the-dcs.html.md.erb
- source/message-flow.html.md.erb
- source/status-response-codes.html.md.erb
`last_reviewed` is out of date.
Just updating `last_reviewed`, nothing else has changed.
> BAU: Update last_reviewed

- source/api-reference.html.md.erb
Everything in here is still correct
Mark this page as reviewed today.
> BAU: Mark API reference page as reviewed

- source/accessibility-statement.html.md.erb
- source/api-reference.html.md.erb
- source/support.html.md.erb
Manual was getting a bit too noisy for my taste.
Update `last_reviewed`
> BAU: Update `last_reviewed`

- source/index.html.md.erb
- source/integrating-with-the-dcs.html.md.erb
- source/message-flow.html.md.erb
- source/message-structure.html.md.erb
Whilst we want to improve the comprehensibility of these docs, they are still accurate.
> BAU: update review dates

- source/api-reference.html.md.erb
- source/index.html.md.erb
- source/integrating-with-the-dcs.html.md.erb
- source/message-flow.html.md.erb
- source/message-structure.html.md.erb
Pull changes from the live site into the test branch.
This is going to spaghettify the history of the test branch, but this can't be helped.
> BAU: merge master into test

- source/handling-responses.html.md.erb
- source/message-structure.html.md.erb
- source/partials/_links.erb
The actual message is wrapped-up in the so-called bento box.  Getting it out is difficult.
Step-by-step guide to handling responses from the DCS.
> A88pU8RK - Handling DCS reponses

- source/integrating-with-the-dcs.html.md.erb
- source/support.html.md.erb
Revert merge to master in favour of test.
Reverts alphagov/dcs-pilot-docs#126
> Revert "lK5rICbK: Add prerequisites for integration"

- source/partials/_links.erb
- source/set-up-jose-cert-thumbprints.html.md.erb
- source/sign-encrypt-dcs-payload.html.md.erb
We need to update pilot docs to describe the generation of JOSE objects.
Updated message structure document.
New document describing generation of thumbprints.
> Bento wrapping

- source/index.html.md.erb
- source/partials/_links.erb
> BAU: Sign-and-encrypt is the only point that isn't a link - make it one.

- source/set-up-jose-cert-thumbprints.html.md.erb
- source/sign-encrypt-dcs-payload.html.md.erb
They aren't in the right order
Reorder them to go:
1. set up thumbrprints
2. sign and encrypt
3. handle responses
> Reorder the docs chapters

- source/set-up-jose-cert-thumbprints.html.md.erb
> BAU: fix links

- source/create-a-network-connection.html.md.erb
Explains how a user creates a network connection to the DCS.
Includes new steps and content to show how a user creates a network connection to the DCS.
Check all technical details are correct. NB this has already been reviewed by 2 tech writers - if substantial changes are made, they will need to review again.
> Network connection

- source/accessibility-statement.html.md.erb
- source/index.html.md.erb
- source/integrating-with-the-dcs.html.md.erb
- source/status-response-codes.html.md.erb
Fixing the last_reviewed, so that we don't get more spam. 🎉 
Nothing much else to add to the PR title, nothing much has changed.
> BAU: Update last_review

- source/access-the-data-in-a-DCS-response.html.md.erb
User needs to know how to access the data in a DCS response
New content on how to access the data in a DCS response
2 tech writers have already reviewed - if there's any substantial changes, they will need to review again
> added 'Access the data in a DCS response' content from gdoc

- source/api-reference.html.md.erb
Passports that expired longer ago will get a validation error.
> Be clear DCS accepts passports that expired up to 18 months ago

- source/integrating-with-the-dcs.html.md.erb
Useful to give a high level overview to ease understanding of what the rest of the docs are telling you.
> Say briefly what a DCS client needs to do

- source/Set-up-your-JOSE-certificate-thumbprints.html.md.erb
- source/api-reference.html.md.erb
- source/sign-and-encrypt-a-DCS-payload.html.md.erb
Dog was being noisy, need to be quiet.
Updating the `last_reviewd` flag, nothing else seems to have been changed lately.
> BAU: update the last_reviewed flag

- source/api-reference.html.md.erb
- source/send-a-test-request-to-the-DCS.html.md.erb
Supply the integration url in the documentation.
Adding the integration URL.
> 9fT1MR50: add integration url

- source/integrating-with-the-dcs.html.md.erb
This is a condition we have not mentioned in the docs. We'll be seeing some integration connections soon so worth being clear about this here.
> Explain you must pass the 'review' stage before you get prod access

- source/generate-keys-and-request-certificates.html.md.erb
> Remind participants to handle keys securely

- source/generate-keys-and-request-certificates.html.md.erb
> Fix broken bullets markdown

- source/access-the-data-in-a-DCS-response.html.md.erb
- source/send-a-test-request-to-the-DCS.html.md.erb
Neither of these pages need updating.
> BAU: Appease the spaniel.

- source/api-reference.html.md.erb
- source/partials/_links.erb
- source/reading-data-from-passport-nfc-chip.html.md.erb
- source/sign-and-encrypt-a-DCS-payload.html.md.erb
- source/support.html.md.erb
API reference needed some user-centred design and updating
Paired with Alex to write this content and update jargon to make the API reference more user-friendly. 
** need to flag: the column width is squashed on the tables. Couldn't find a way to resolve this - any tips welcome**
> Api reference

- config/tech-docs.yml
We're not using it
Remove Google Analytics
> BAU: Remove Google analytics

- source/Set-up-your-JOSE-certificate-thumbprints.html.md.erb
- source/create-a-network-connection.html.md.erb
- source/generate-keys-and-request-certificates.html.md.erb
- source/sign-and-encrypt-a-DCS-payload.html.md.erb
Perform the regularly scheduled review of these pages.
Fix a few typos and formatting errors. Also switch to review in 2 months.
> BAU: review pages due for review

- Gemfile.lock
- source/integrating-with-the-dcs.html.md.erb
Need documentation about what responses mean on the DCS
Documents what the DCS responses mean.
> added gdoc content about DCS responses

- source/access-the-data-in-a-DCS-response.html.md.erb
- source/api-reference.html.md.erb
Needed links pointing users towards what a DCS response means. 
Included links pointing towards https://dcs-pilot-docs.cloudapps.digital/integrating-with-the-dcs/#understand-what-responses-mean-when-making-a-dcs-check
> added links about what a DCS response means

- source/accessibility-statement.html.md.erb
- source/status-response-codes.html.md.erb
Daniel prompted for a review of the accessibility statement and the response status code pages.
Both pages are fine. The accessibility statement has been checked with the accessibility team.
> BAU: Daniel the Manual Spaniel review 2020-07-14

- source/accessibility-statement.html.md.erb
- source/status-response-codes.html.md.erb
The documentation is reasonably stable now, so reviewing less frequently is probably something we can do.
Reduce review freqency of Accessibililty and State Response Code pages to 3 months.
> BAU: Reduce review frequency

- source/integrating-with-the-dcs.html.md.erb
Regular review as prompted by Daniel the Manual Spaniel.
Review the "How the DCS works" page, no changes required, bumping review date.
> BAU: Review the How the DCS works page

- source/Set-up-your-JOSE-certificate-thumbprints.html.md.erb
- source/create-a-network-connection.html.md.erb
- source/generate-keys-and-request-certificates.html.md.erb
- source/support.html.md.erb
Daniel the Manual Spaniel prompted us to review four of our guides:
- Generate keys and request certificates
- Create a network connection to the DCS
- Set up your JOSE certificate thumbprints
- Support
Nothing has changed in the processes these guides describe since they were last reviewed, so I have simply bumped the 'last reviewed' date to today for each of them.
> Bump review dates for guides in latest Spaniel prompt

- source/enrol-with-the-DCS-certificate-authority.html.md.erb
No change to this process since we published this
> Bump review date on enrolment guide

- source/api-reference.html.md.erb
- source/reading-data-from-passport-nfc-chip.html.md.erb
Review prompted by Manual Spaniel.
No changes required, review dates updated.
> BAU: Spaniel prompted review

- source/api-reference.html.md.erb
Pilot clients will be able to diagnose errors on their side more easily if we explain what each error means.
A table of all possible validation error messages for Passport Validation requests
> AfMQJza1: Add table of possible validation error messages

- README.md
The new section has been reviewed by a tech-writer and changes have been suggested.
Update the wording in the new section on how to fix the `ffi` issue as per suggestions from @PippaClarkGDS.
> BAU: Update wording for `ffi` fix.

- source/getting-access-to-production.html.md.erb
- source/integrating-with-the-dcs.html.md.erb
We've been in touch with some organisations about what they need to do to get access to production. We should explain that in our documentation.
> Explain how to request access to production

- source/access-the-data-in-a-DCS-response.html.md.erb
- source/index.html.md.erb
- source/integrating-with-the-dcs.html.md.erb
- source/send-a-test-request-to-the-DCS.html.md.erb
- source/status-response-codes.html.md.erb
Regular review prompted by Daniel the Manual Spaniel.
Minor change to the 'Send a test request page'; replace `valid true`(and similar) with `valid: true` in line with other pages.
Expand JWE acronym in 'Access the data in a DCS response' page
Spelling corrections on the 'Access the data in a DCS response' page.
Bump reviews dates of all other pages
Not required
> Bau spaniel review 2020 10 19

- source/validating-your-users-data.html.md.erb
Gap in documentation currently about how pilot participants should be validating their users' data
Includes guidance pilot participants can follow to validate their users' data, including link to the error codes that can occur.
> uploaded gdoc content about validating users' data

- source/Set-up-your-JOSE-certificate-thumbprints.html.md.erb
- source/api-reference.html.md.erb
- source/create-a-network-connection.html.md.erb
- source/enrol-with-the-DCS-certificate-authority.html.md.erb
- source/generate-keys-and-request-certificates.html.md.erb
- source/reading-data-from-passport-nfc-chip.html.md.erb
- source/sign-and-encrypt-a-DCS-payload.html.md.erb
Bump the review dates on pages that need reviewing.
Some minor grammar changes and sentence ordering modifications.
> BAU: Appease the spaniel's review requests

- source/support.html.md.erb
Spaniel prompted review of Support page
All looks ok as discussed with @benjamin-mortimer so update next review date.
> BAU: Spaniel review of Support page

- source/getting-access-to-production.html.md.erb
Regular review as prompted by the manual spaniel.
No changes required to the "getting access to production" page, bumping review to 6 months.
> BAU: Spaniel Review 2020-12-07 - Access to Production

- source/Set-up-your-JOSE-certificate-thumbprints.html.md.erb
- source/access-the-data-in-a-DCS-response.html.md.erb
- source/api-reference.html.md.erb
- source/create-a-network-connection.html.md.erb
- source/enrol-with-the-DCS-certificate-authority.html.md.erb
- source/generate-keys-and-request-certificates.html.md.erb
- source/helping-your-users.html.md.erb
- source/integrating-with-the-dcs.html.md.erb
- source/reading-data-from-passport-nfc-chip.html.md.erb
- source/send-a-test-request-to-the-DCS.html.md.erb
- source/sign-and-encrypt-a-DCS-payload.html.md.erb
- source/status-response-codes.html.md.erb
- source/validating-your-users-data.html.md.erb
The content is largely complete at this point, and reviews will be done as and when needed / requested rather than on short fixed cadence.
> zA9yfoil: Mass set review date at 6 months

- source/accessibility-statement.html.md.erb
The Tech Docs Template has now had its accessibility fixes fixed and we need to reflect this in the Document Checking Service's accessibility statement.
Updates wording in some sections in the accessibility statement which reflects that the documentation is now fully compliant.
> updates accessibility statement with full compliance
