alphagov/dcs-pilot-docs

- Staticfile.auth
Once released, we don't want the docs to be behind username and 
password.
> Remove Staticfile.auth

- README.md
Add 'Code of conduct' section in README.
This section links to the `alphagov` Code of conduct.
This follows the pattern found in other `alphagov` repos.
> Add Code of conduct

- source/integrating-with-the-dcs.html.md.erb
- source/message-structure.html.md.erb
- source/partials/_links.erb
The `x5t` and `x5t#256` headers are optional in the RFC but mandatory for the DCS, as we use them to confirm that the certificate used to sign/encrypt is part of a safe-list on the DCS.
> BAU: Improve documentation for thumbprint headers.

- Gemfile.lock
Did a `bundle update` to get the latest version of the tech docs gem, `govuk_tech_docs 2.0.5`
Using the latest version provides us with the latest features and patches 😉
> Update gem to govuk_tech_docs 2.0.5

- config/tech-docs.yml
- source/javascripts/application.js
Show the last [reviewed date](https://tdt-documentation.london.cloudapps.digital/page-expiry.html#page-expiry-and-review) for each page.
Doing this to increase users' confidence that they're seeing up-to-date content.
> Show last reviewed date for each page in the docs

- config/tech-docs.yml
Add missing `https://` to the host config in `config/tech-docs.yml`.
So proper URLs can be generated based on the configured host.
For example, not having the `https://` means Daniel the Manual Spaniel can't produce valid links:
> Fix host configuration

- source/message-structure.html.md.erb
- source/partials/_links.erb
* We were informed by 🐶 that `Message Structure` needs reviewing
* Taking stock of the writing workshop, we have moved the structure of the message itself to the top of the page as it's the focus of the content. It was previously at the bottom.
> BAU: Review `Message Structure` and update content flow

- config.rb
- source/message-flow.html.md.erb
- source/message-structure.html.md.erb
Middleman defaults to introducing automatic `alt` tags based on the file name. This is not meaningful alt text.
When writing documentation, we always try to have the information in the image also present in the surrounding text. If this is not possible, then we write meaningful `alt` text.
However, in most cases, images in documentation are described in surrounding text so most of the time we need empty `alt` tags.
Relevant W3C guidance: https://www.w3.org/WAI/tutorials/images/decorative/
* remove the linter check that looks for the existence of `alt` text
* add empty `alt` tags for all the images in these docs that are described in the surrounding text
Check that:
* all the images with empty `alt` tags in these docs are described in surrounding text
* `alt` tags are indeed empty in the …
> Fix alt tags and settings

- source/message-structure.html.md.erb
I recognised that we had incorrectly documented how the a payload is structured.
Previously, the pilot docs suggested that a client using DCS would use their private encryption key to encrypt their payload.
This is incorrect, as it would mean that the DCS would be unable to decrypt the payload.
The correct structure of a payload would be:
- signed object using private signing key
- encrypted payload using DCS's public encryption certificate
- signed content with private signing key
> BAU: Fix incorrect wording

- source/status-response-codes.html.md.erb
DCS returns different HTTP response codes to those currently described in the pilot docs. 
This is partly because of our rate limiting work and partly because of removing 'planned outage' responses for HMPO's system.
Updated the status codes documentation to be clear that you now get:
+ 503 when the collective rate limit for all pilot clients is exceeded
+ 429 when you've exceeded your individual client rate limit, as well as when you've exceeded your quota
Please fact check that these are indeed the responses we send.
> Rate limit

- source/message-structure.html.md.erb
Remove duplicated header paragraph
These headers are needed for the signing layers, but are not needed for encryption. Remove this paragraph to reduce confusion. The header is still documented in the signing section above.
> BAU: remove unnecessary headers

- source/api-reference.html.md.erb
Pilot participants should be aware there is a rate limit for DCS and what the limit is.
Adds a short section to the API reference page describing the rate limit and the HTTP status codes users receive in the event it is exceeded.
> Add section on rate limits

- .travis.yml
- README.md
Currently, it's just a mirror of master but I'll soon submit a PR to change it to do what the README now says it does.
This will allow us to make changes that we can validate with user testing before updating the 'live' version of the docs.
The username/password are not for security - they're just to make it less likely that a pilot participant mistakes the prototype for the real thing.
Also fix some typos etc. in the readme.
> uSnau9tK: setup test branch for prototyping

- .travis.yml
- README.md
- manifest.yml
- source/Staticfile.auth
This follows on from #111, which set things up on master to enable us to create a test version of the site on the 'test' branch. We'll use this for prototyping things for user research before feeding them into the live version of the docs.
There's a simple username/password (test/test) to reduce the risk of people confusing the test site with the live site.
Pull in changes from master. Change config to new URL/PaaS app and [credentials](https://tdt-documentation.london.cloudapps.digital/publish_project/deploy/#add-basic-authentication).
> Deploy test site for user research

- source/api-reference.html.md.erb
We do not use this field for anything - we just record it in our logs. This field is optional. Thus, we can omit it from the pilot docs. This should save pilot participants the effort of providing the field, and us the effort of needing to provide them with the value.
Remove all mentions of the client ID from the docs.
> BAU: remove references to 'clientId' from the docs

- source/message-structure.html.md.erb
This is the same as `RSA-OAEP`, except it uses SHA256 instead of SHA1. Both algorithms are still secure - despite SHA1 being now considered weak, it is [only used as an entropy source](https://eprint.iacr.org/2006/223.pdf), so doesn't need to be collision-resistant.
It is still good to officially document support for both, though. Some libraries mark `RSA-OAEP` as deprecated, but support for `RSA-OAEP-256` is not yet ubiquitous. The DCS already supports both, so there's no extra work for us to do.
In the long term, we might want to consider switching from RSA-based algorithms to elliptic-curve-based algorithms. This is because [RSA is generally considered harder to implement correctly](https://blog.trailofbits.com/2019/07/08/fuck-rsa/). However, we're not going to do that now, since it …
> BAU: add support for `RSA-OAEP-256` encryption

- source/api-reference.html.md.erb
- source/message-flow.html.md.erb
- source/message-structure.html.md.erb
- source/set-up-mtls-to-dcs.html.md.erb
- source/support.html.md.erb
Setting up mTLS to DCS was one of the things users struggled with in the lab. We decided to address this with a detailed step by step guide.
Adds a new guide to the docs that walks you through setting up an mTLS connection to DCS, including commands you can use and sample responses.
Also bumps the page weights so it appears in the right place in the navigation. We're going to add some more guides so I've just bumped everything up by 10 points to make room.
Please check for factual accuracy.
NB: This guide should contain a link to another guide about raising certificates, which we haven't created yet. I've left it pointing to `/` and created a story in the backlog to update it when the real guide exists.
> Add a guide to setting up mutual TLS to DCS

- source/set-up-mtls-to-dcs.html.md.erb
Some content was not rendering correctly in a browser.
Tweaked formatting for the curl command.
Added some hyperlinks for curl and Postman.
Consistent formatting for the dcs url placeholder and http status codes.
> l237hSIY - Formatting tweaks to the mTLS docs

- source/generating-keys-and-csrs.html.md.erb
- source/set-up-mtls-to-dcs.html.md.erb
Documentation needs more detailed instruction and how to generate keys and obtain required certificates.
Add new page describing end to end process for generating a private
keys, CSRs and submitting to CA.
Update links to this page on other pages.
Describe the changes you're proposing.
> DOCATHON: Add generating keys and certs page

- source/integrating-with-the-dcs.html.md.erb
- source/support.html.md.erb
Previously we didn't have a clear definition of what was required before a participant started to create their clients.
This commit adds such a list, with focus on outlining what certificates and keys are required before starting their onboarding process. It also clearly defines which keypairs are provided (by us) and which ones they will have to manually create themselves (or submit CSRs).
I've also added a section to the support section to help define what we expect to see from a pilot participant when they are asking for help.
`./preview-with-docker.sh`
> lK5rICbK: Add prerequisites for integration

- source/api-reference.html.md.erb
- source/code/dcs-passport-check-request-payload.json-schema.json
- source/partials/_links.erb
The json-schema provided can be used to validate json payloads are structured and formatted correctly.
Add json-schema for passport check request payload JSON to API reference with links to validators.
> YC3GlILa - Add json-schema for passport check request payload JSON to API reference 

- source/index.html.md.erb
- source/integrating-with-the-dcs.html.md.erb
- source/partials/_links.erb
The "Integrating with DCS" guide provided some high-level information about the process you'd follow to connect up to DCS for the pilot. Most of that is covered in more detail with the new guides we've written since the lab day.
+ deletes the "Integrating with DCS" guide 
+ retains some of the content in simplified form and moves it to the homepage
+ remove some content from the homepage and simplify what's left
I don't think I've deleted something crucial, but might be worth a quick check.
I think I'll need help with some merge conflicts too...
> Remove "Integrating..." section and put all overview content on the homepage

- source/integrating-with-the-dcs.html.md.erb
DCS signing certificate is used by the client to validate DCS response signatures.
Update usage of DCS signing certificate
> lK5rICbK - Update usage of DCS signing certificate

- source/integrating-with-the-dcs.html.md.erb
Some content is duplicated in the step by step certificates guide we now have, and on the homepage. (My previous PR to delete it had some merge conflict funny business).
Deletes the 'integrating to DCS' content that's now on the homepage
Removes CSR guidance from the prerequisites and replaces it with a link to the step by step guide
Renames the guide, since it's no longer about 'integrating' as such
> Finesse the 'prerequisites' guide

- source/Set-up-your-JOSE-certificate-thumbprints.html.md.erb
- source/sign-and-encrypt-a-DCS-payload.html.md.erb
We'd referenced "your library" a few times without explicitly saying you need to use one. This should avoid some confusion.
This PR adds a short section to the 'sign and encrypt' guide to tell users they need to pick a library. We should come back another time with some recommendations for common languages.
It also adds a note to the 'thumbprints' guide to say you don't need to generate them if your library will do it for you, which might save some users some time.
> Tell users they need to use a JW* library

- source/api-reference.html.md.erb
- source/partials/_links.erb
- source/status-response-codes.html.md.erb
We provide this header when a user hits a rate limit to help them know how long to wait before trying again.
Document the use of the `Retry-After` header.
> 66OPHmaD: document new Retry-After header

- source/integrating-with-the-dcs.html.md.erb
Just reading through, it seems odd that we call out mutual auth with its own paragraph - it's not the only thing you have to do to connect and nor is it the most difficult, so it reads oddly for it to be given this prominence.
I thought about writing a little bit of detail for each of the things in the list, but that doesn't seem to add much so I thought it was simpler to just remove this para.
Deletes the 'Using mutual authentication to connect' paragraph from the 'How DCS works' section.
@PippaClarkGDS what do you think?
> Remove mutual auth paragraph from intro

- source/api-reference.html.md.erb
- source/partials/_links.erb
- source/status-response-codes.html.md.erb
Pilot clients have quotas that limit the total number of checks they can make. We need to document how this works and how clients can find out information on their usage.
Note that this only applies to pilot clients - our existing clients do not have quotas.
Explain what quotas are and how they appear for pilot clients. Document the headers clients can use to monitor their usage.
> G7RK6f1q: document how quotas work

- source/sign-and-encrypt-a-DCS-payload.html.md.erb
From our user research, we've seen that users appreciate knowing which JOSE libraries are known to work with the DCS.
Be careful with the working to make it clear that we've tested that they work. Do not recommend using any particular library as we have not done enough in-depth investigation of them to check that they are suitable (e.g. secure, well-maintained, licensing).
Document the libraries with which I am certain that we have made successful DCS checks.
I've tested the clients written in Python and Java, so know that they work against the DCS. For the other languages, I've consulted with the people who wrote clients using those languages - see the individual commits for details.
Note that we had a number of user research participants attempt to use Ruby to connect to the DCS. …
> kvMZlCZz: document JOSE libraries we've tested

- source/api-reference.html.md.erb
We added these headers to help clients understand how they were using their rate limit. Document what clients should look for.
Document the new rate limit headers. Split the rate limit section with some new h3s.
> 52O7YkqU: document new rate-limit headers

- source/index.html.md.erb
Removed the 'connecting window' concept as we don't really use this - we're just going to connect people.
> Change connection start date to acknowledge delays

- source/create-a-network-connection.html.md.erb
The request libraries used by DCS clients need to support custom CA bundles and client certificates. Sometimes this is in the standard library for the language, sometimes it requires a third-party library.
Add list of libraries that we know work.
> OfyWrLjK: Recommend libraries to perform HTTPS requests

- source/api-reference.html.md.erb
- source/partials/_links.erb
- source/sign-and-encrypt-a-DCS-payload.html.md.erb
Make it clear that correlationId, requestId, and timestamp need to be generated by clients within their application.
* Add very minor information - almost all programming languages support generating uuids and timestamps in the correct format.
* Fix minor error in _link.erb where the ISO is mis-numbered
`./preview-with-docker.sh` and navigate to `http://localhost:4567/sign-and-encrypt-a-DCS-payload/#build-a-plain-json-payload`
> BR9gNJHs: Add information about generating request-specific data in the payload

- source/create-a-network-connection.html.md.erb
- source/generate-keys-and-request-certificates.html.md.erb
- source/support.html.md.erb
Reviewed the 3 guides whose dates have come up and nothing has changed in what users have to do for those things. Have created a documentation card in the backlog to clarify the opening of the "Create a network connection" guide, however.
> Appease the Spaniel

- source/send-a-test-request-to-the-DCS.html.md.erb
currently a gap in the docs. This doc plugs the gap by outlining how users can test their client works by sending test requests. 
Page which explains how a user can send different test requests to the DCS. 
Already been reviewed by 2 tech writers. If there's substantial changes, will need to get them to review again.
> uploaded the gdoc content for sending a test request

- source/send-a-test-request-to-the-DCS.html.md.erb
Error and Valid:True cases were the wrong way round. Also update the fictional sample data with current stub records.
This also ensures `requestId` is consistent between requests and responses
`./preview-with-docker.sh` and navigate to `/send-a-test-request-to-the-DCS/#send-a-test-request-to-the-dcs`
> fvUEqNi7: Ensure the correct sample data is attributed to each sample response

- source/sign-and-encrypt-a-DCS-payload.html.md.erb
It's 'typ', not 'type' - see https://tools.ietf.org/html/rfc7516#section-4.1.11
> BAU: use correct header name

- source/partials/_links.erb
- source/sign-and-encrypt-a-DCS-payload.html.md.erb
Be more permissive where possible to make life easier for new clients.
Stop recommending an encryption algorithm that is considered deprecated.
* Be more permissive in the JWS alg header and the JWE enc header. The permissable alternatives are all supported by the DCS and are at least as secure as the one we originally recommended.
* Change the JWE alg header to mandate the more secure version of the header. `RSA-OAEP` is still valid, but it uses SHA-1, so is widely considered deprecated. We should therefore discourage new clients from using it.
* Update a link to a draft RFC to the final approved RFC.
* As per RFC 7518, JOSE stands for 'JSON Object Signing and Encryption'. Update accordingly.
> BAU: update guidance on algorithms

- source/api-reference.html.md.erb
There is no request body, and the response is plain JSON.
> BAU: Status (GET) requests do not need `Content-Type: application/jose`

- source/api-reference.html.md.erb
Since the rate limit text was first written, we have agreed our initial rate limit. Since we now know how long the window will be, we can tell clients to help them prepare.
We cannot give a precise number at this stage. Commercial confidentiality means we will be unable to until all possible pilot participants have decided one way or the other. In the interim, use an indicative number that is within an order of magnitude of the expected final number (i.e. in the range 1 to 100).
Provide more guidance on the expected rate limit for pilot participants.
> H3WCW3iA: provide more detail on rate limits

- CODEOWNERS
@benjamin-mortimer has been doing a lot of of docs work lately. It seems like an oversight that he is unable to approve PRs in this repo.
Make everyone in the [verify-dcs-docs](https://github.com/orgs/alphagov/teams/verify-dcs-docs) team a code owner. Ben and Beth (?) are the only people who will be affected by this. They will now have the power to approve PRs for this repo. They still won't be able to merge PRs, though.
Membership of the verify-dcs-docs team is managed in terraform.
> FjWF1vJ0: give Ben and Beth approval rights

- source/api-reference.html.md.erb
- source/index.html.md.erb
- source/status-response-codes.html.md.erb
Review prompted by Daniel the Manual Spaniel.
Update review dates.
Include entry on `status-response-codes` page for `400` (Bad request), this should probably be fleshed out in a story.
Removed references to `503` planned outage and planned outage functionality in status responses as this is a deprecated feature.
> BAU: Scheduled review requested by the spaniel

- source/partials/_links.erb
- source/reading-data-from-passport-nfc-chip.html.md.erb
- source/support.html.md.erb
It's possible to run into issues when checking evidence where data has been retrieved from the NFC chip or machine-readable zone rather than input manually.
Explain the issue, why it happens, and ways to resolve it
Run `./preview-with-docker.sh` and navigate to `http://localhost:4567/reading-data-from-passport-nfc-chip/#reduce-errors-when-using-data-from-a-passport-chip` in your browser
> TLwofDx4: Content to explain issues with using NFC-based passport data

- .github/dependabot.yml
We want to make sure we keep our dependencies up to date. This will reduce our exposure to potential security vulnerabilities and let us fix them more quickly.
We use Dependabot for this, following the other DCS-related repositories.
Add daily checks by Depenabot for our Ruby dependencies.
> G34uCPYu: add Dependabot

- source/create-a-network-connection.html.md.erb
The second paragraph is slightly confusing, or so I thought in May: https://trello.com/c/WYEeGn8M/414-make-opening-sentence-of-mtls-guide-clearer
Makes a small changing to the wording so that it no longer introduces a new concept as though it was known.
Also: moved a repeated 'to' from a bulleted list into its lead-in, and changed 'convert' to 'converting' in a heading, as it's not an instruction you have to follow, just information in case you need to do that thing.
Is this still factually accurate?
> Tweak opening of mTLS guide (plus small style edits)

- source/support.html.md.erb
Clients should be able to use this to find out the current status of the DCS and subscribe for incident notifications.
Add a link to the GOV.UK Verify status page
> BAU: add link to status page

- source/enrol-with-the-DCS-certificate-authority.html.md.erb
- source/index.html.md.erb
Need documentation about how a user can enrol with the DCS certificate authority. 
Documentation about how a user can enrol with the DCS certificate authority.
> add gdoc content about enrolling with the DCS certificate authority

- config.rb
- test.rb
There are two ways of adding a link:
1. directly - `[foo](bar.com)`
2. using the [links partial](https://github.com/alphagov/dcs-pilot-docs/blob/master/source/partials/_links.erb) - `[bar]` or `[foo][bar]`, where the link partial has an entry for `[bar]` that points to `bar.com`.
We've previously had problems with broken links. This is solved for case 1, since html-proofer catches those. However, it is not able to catch broken links created by case two. These manifest as seeing `[foo][bar]` still present in the HTML output.
Add a linter to automatically catch these errors to reduce the amount of manual checking required.
Create a new html-proofer checker that checks for broken links that try (but fail) to use the link partial.
This is a copy of the linter that we already using …
> BAU: add custom lint for broken link partial use

- source/generate-keys-and-request-certificates.html.md.erb
Adds a sentence to redirect users to the CA enrollment guide if they've come to the "generate keys and certificates" page first. Saves users wasting time raising a CSR that we won't be able to approve.
> Say you must enrol with the CA before you can raise a CSR

- .secrets.baseline
For https://github.com/alphagov/gds-pre-commit/
Add a secret baseline - none of the things detected by `detect-secrets` are actually secret.
> ow4AXjYw: add secret baseline

- source/access-the-data-in-a-DCS-response.html.md.erb
- source/api-reference.html.md.erb
- source/reading-data-from-passport-nfc-chip.html.md.erb
- source/send-a-test-request-to-the-DCS.html.md.erb
Bumps review dates on four guides:
- Reduce errors when using data from a passport chip
- API reference
- Send a test request to the DCS
- Access the data in a DCS response
I had a read through each one and to my knowledge the content is still current and up to date.
> Appease Daniel the Manual Spaniel

- source/Set-up-your-JOSE-certificate-thumbprints.html.md.erb
- source/sign-and-encrypt-a-DCS-payload.html.md.erb
These docs claim that we mandate both SHA1 and SHA256 thumbprint headers in the JWS payload layers, while this isn't strictly true.
This PR removes references to SHA1 from the doc as SHA256 is the preferred thumbprint.
> 7LG7Kop7: Remove SHA1 thumbprint as a necessary JWS header

- .secrets.baseline
- source/Set-up-your-JOSE-certificate-thumbprints.html.md.erb
- source/partials/_links.erb
- source/sign-and-encrypt-a-DCS-payload.html.md.erb
We no longer need the SHA1 header in JWEs. Remove the requirement to save new clients some work. If clients choose to send the header, that's fine - we'll just ignore it.
This follows on from https://github.com/alphagov/dcs-pilot-docs/pull/203, which did the same for JWS.
DCS people - look at Decrypter.java to see how the header is/was used.
Remove the requirement to provide the `x5t` (SHA1) header in JWEs.
Also remove some unused links and un-pluralise instances of 'thumbprints'.
> BAU: remove requirement for SHA1 header in JWEs

- source/enrol-with-the-DCS-certificate-authority.html.md.erb
Pilot participants need to sign a contract before they can begin the CA enrolment process. We should point this out in our documentation.
> Explain you must sign a contract before enrolling

- source/integrating-with-the-dcs.html.md.erb
We added a guide to the pilot docs about how to enrol with the DCS certificate authority. But we didn't add enrolling with the CA to the list of steps participants take to integrate with DCS. It's an important step and comes with a lead time, so I've added it.
> Add enroling with the DCS CA to the list of steps to integrate with DCS

- source/sign-and-encrypt-a-DCS-payload.html.md.erb
Wording about diagrams should not reference the diagram for accessibility reasons. 
Removes mention of the diagram from the text.
> Change wording about diagram to meet accessibility requirements

- source/accessibility-statement.html.md.erb
Need specific headings in our accessibility statement to make any non-compliances clear.
Need specific headings in our accessibility statement to make any non-compliances clear.
> fixed headings in accessibility to be compliant with regulations

- source/generate-keys-and-request-certificates.html.md.erb
Not very clear that a user has to enrol with DCS CA before raising a CSR
Moved section further up and removed confusing information to make user focus on what they need to do
> made it more clear that a user will have to enrol with the DCS CA before they can raise a CSR

- README.md
There are known issues running Middleman on the latest versions of MacOS, we should document the way to fix this issue.
Add a brief section about running Middleman natively on MacOS and the `ffi` library compatibility issues.
> BAU: Add a running on MacOS section to the README

- source/send-a-test-request-to-the-DCS.html.md.erb
Inform pilot participants of additional testing records.
Describe a sample passport with multiple forenames, as is permitted in the spec.
> LOM6in1z: Add example with multiple forenames

- source/api-reference.html.md.erb
Users getting confused when `scheduledOutages` field is empty
> included a line about how scheduledOutages field will be empty for pilot participants

- source/api-reference.html.md.erb
- source/helping-your-users.html.md.erb
No documentation about how pilot participants can help answer their users' passport queries. 
Documentation giving advice and guidance about how pilot participants can best help their users answer their passport queries. 
If any major changes are suggested, this will have to go back through tech writer review.
> uploaded gdoc content and created a page in docs

- source/api-reference.html.md.erb
- source/integrating-with-the-dcs.html.md.erb
2 places in the docs explaining what a DCS response means is confusing for the user. 
Moved the detail about the DCS responses to the API reference and included a link to direct users there from the more general overview in 'How the DCS works' 
Sense check it makes sense for the detailed information about the DCS responses to be in the API reference
> moved detailed information about DCS responses into the API reference … and included a link to direct users there from the DCS responses page

- source/index.html.md.erb
The docs homepage references things that are currently happening as though they were going to happen in future. It also refers to "early 2020" as being in the future, but this date is now in the past.
> Change homepage tenses from future to present

- source/accessibility-statement.html.md.erb
We mentioned the tech docs template accessibility issues should be fixed by 31 Dec 2020 but the date will now be March 2021.
Updated the line to reflect the new date.
> updating accessibility statement review date to March 2021

- source/Set-up-your-JOSE-certificate-thumbprints.html.md.erb
Update  "Set up your JOSE certificate thumbprints" doc to fix misleading text.
The certificate thumbprint is used *when* signing and encrypting DCS payloads, not *to* sign and encrypt DCS payloads.
> BAU: Fix misleading text

- source/rotating-keys-and-certificates.html.md.erb
We need documentation that explains cert rotations to DCS clients.
Add documentation to help DCS clients understand certificate rotation processes.
> zyMOmoE7: Add cert rotation doc

- source/access-the-data-in-a-DCS-response.html.md.erb
- source/generate-certificate-thumbprints.html.md.erb
- source/integrating-with-the-dcs.html.md.erb
- source/rotating-keys-and-certificates.html.md.erb
- source/sign-and-encrypt-a-DCS-payload.html.md.erb
The document contains a link labeled "a JOSE object" that points to documentation about how to create a certificate thumbprint. This is confusing. We should change it.
We do not have a document the simply explains what a JOSE object is, furthermore we rarely mention JOSE and can avoid doing so.  So we will remove all references to JOSE in our text. Technical uses in `Content-Type` and names of libraries remain, without comment.
Does this all make sense?
> BAU: Remove confusing link and references to JOSE

- source/rotating-keys-and-certificates.html.md.erb
The document mistakenly specifies using an "integration encryption certificate" when the environment is not relevant.
Remove reference to `integration`.
> BAU: Remove reference to integration
